version: "3.9"
   
services:
#  db:
#    image: postgres:13
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    ports:
#      - 5432:5432
#    environment:
#     - "POSTGRES_HOST_AUTH_METHOD=trust"
#    restart: always
#  pgadmin:
#    image: dpage/pgadmin4
#    ports:
#      - 5050:80
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@sicombue.com
#      - PGADMIN_DEFAULT_PASSWORD=Sicombue1.
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
 #   environment:
 #     - POSTGRES_NAME=postgres
 #     - POSTGRES_USER=postgres
 #     - POSTGRES_PASSWORD=postgres
#    depends_on:
#      - db