# Generated by Django 3.2.4 on 2023-09-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollfile',
            old_name='file',
            new_name='file_uri',
        ),
        migrations.RenameField(
            model_name='payrollimage',
            old_name='picture',
            new_name='picture_uri',
        ),
    ]
